# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_about_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(787, 475)
        Form.setStyleSheet(
            "QWidget {background-color: #1581e6; color: white; font-family: \"Days\";}\n"
            "QPushButton:hover {border-style: solid; border-width: 3px; border-color: white;} QPushButton:pressed {border-style: solid; border-width: 3px; border-color: rgb(14, 80, 158);} \n"
            "QPushButton {font-size: 28px; background-color: rgb(255, 230, 31); color: rgb(14, 80, 158); border-radius: 10px; height: 60px; width: 300px}\n"
            "QLineEdit {border-radius: 10px; border-style: solid; border-width: 1px; border-color: white;}\n"
            "QLineEdit:hover {border-style: solid; border-width: 3px; border-color: white;}\n"
            "QLineEdit:focus {border-style: solid; border-width: 3px; border-color: white;}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 11)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(226, 0))
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.name_line = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.name_line.setFont(font)
        self.name_line.setReadOnly(True)
        self.name_line.setObjectName("name_line")
        self.horizontalLayout_2.addWidget(self.name_line)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.wrong_name = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.wrong_name.sizePolicy().hasHeightForWidth())
        self.wrong_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.wrong_name.setFont(font)
        self.wrong_name.setStyleSheet("color: rgb(255, 0, 4);")
        self.wrong_name.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.wrong_name.setObjectName("wrong_name")
        self.verticalLayout.addWidget(self.wrong_name)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(226, 0))
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.surname_line = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.surname_line.setFont(font)
        self.surname_line.setReadOnly(True)
        self.surname_line.setObjectName("surname_line")
        self.horizontalLayout_3.addWidget(self.surname_line)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.wrong_surname = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.wrong_surname.sizePolicy().hasHeightForWidth())
        self.wrong_surname.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(12)
        self.wrong_surname.setFont(font)
        self.wrong_surname.setStyleSheet("color: rgb(255, 0, 4);")
        self.wrong_surname.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.wrong_surname.setObjectName("wrong_surname")
        self.verticalLayout.addWidget(self.wrong_surname)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(83, 0))
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.login_line = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.login_line.setFont(font)
        self.login_line.setReadOnly(True)
        self.login_line.setObjectName("login_line")
        self.horizontalLayout_4.addWidget(self.login_line)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(226, 0))
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.password_line = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.password_line.setFont(font)
        self.password_line.setReadOnly(True)
        self.password_line.setObjectName("password_line")
        self.horizontalLayout_5.addWidget(self.password_line)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.wrong_password = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.wrong_password.sizePolicy().hasHeightForWidth())
        self.wrong_password.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(12)
        self.wrong_password.setFont(font)
        self.wrong_password.setStyleSheet("color: rgb(255, 0, 4);")
        self.wrong_password.setText("")
        self.wrong_password.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.wrong_password.setObjectName("wrong_password")
        self.verticalLayout.addWidget(self.wrong_password, 0,
                                      QtCore.Qt.AlignTop)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 11)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_edit_info = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_edit_info.sizePolicy().hasHeightForWidth())
        self.btn_edit_info.setSizePolicy(sizePolicy)
        self.btn_edit_info.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_edit_info.setObjectName("btn_edit_info")
        self.horizontalLayout.addWidget(self.btn_edit_info)
        self.btn_save_info = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_save_info.sizePolicy().hasHeightForWidth())
        self.btn_save_info.setSizePolicy(sizePolicy)
        self.btn_save_info.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_save_info.setObjectName("btn_save_info")
        self.horizontalLayout.addWidget(self.btn_save_info)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "О себе"))
        self.label_3.setText(_translate("Form", "Имя"))
        self.wrong_name.setText(
            _translate("Form", "Имя должно состоять из букв из цифр"))
        self.label_2.setText(_translate("Form", "Фамилия"))
        self.wrong_surname.setText(
            _translate("Form", "Фамилия должна состоять из букв из цифр"))
        self.label.setText(_translate("Form", "Email / Логин"))
        self.label_4.setText(_translate("Form", "Пароль"))
        self.password_line.setPlaceholderText(
            _translate("Form", "Введите новый пароль"))
        self.btn_edit_info.setText(_translate("Form", "Редактировать"))
        self.btn_save_info.setText(_translate("Form", "Сохранить"))
