# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 800)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QWidget {background-color: #1581e6; color: white; font-family: \"Days\";}\n"
"QPushButton:hover {border-style: solid; border-width: 3px; border-color: white;} QPushButton:pressed {border-style: solid; border-width: 3px; border-color: rgb(14, 80, 158);} \n"
"QPushButton {background-color: rgb(255, 230, 31); color: rgb(14, 80, 158); border-radius: 10px;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QVBoxLayout(self.centralwidget)
        self.tabs.setObjectName("tabs")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(45, 35, 45, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_profile = QtWidgets.QPushButton(self.centralwidget)
        self.btn_profile.setEnabled(True)
        self.btn_profile.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_profile.setFont(font)
        self.btn_profile.setObjectName("btn_profile")
        self.horizontalLayout.addWidget(self.btn_profile)
        self.btn_pretest = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pretest.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.btn_pretest.setFont(font)
        self.btn_pretest.setObjectName("btn_pretest")
        self.horizontalLayout.addWidget(self.btn_pretest)
        self.btn_rating = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rating.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.btn_rating.setFont(font)
        self.btn_rating.setObjectName("btn_rating")
        self.horizontalLayout.addWidget(self.btn_rating)
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_exit.sizePolicy().hasHeightForWidth())
        self.btn_exit.setSizePolicy(sizePolicy)
        self.btn_exit.setMinimumSize(QtCore.QSize(70, 70))
        self.btn_exit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Знак Выхода.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_exit.setIcon(icon)
        self.btn_exit.setObjectName("btn_exit")
        self.horizontalLayout.addWidget(self.btn_exit)
        self.tabs.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главная"))
        self.btn_profile.setText(_translate("MainWindow", "Профиль"))
        self.btn_pretest.setText(_translate("MainWindow", "Тестирование"))
        self.btn_rating.setText(_translate("MainWindow", "Рейтинг"))
