# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_registration_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(778, 293)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setStyleSheet("QWidget {background-color: #1581e6; color: white; font-family: \"Days\";}\n"
"QPushButton:hover {border-style: solid; border-width: 3px; border-color: white;} QPushButton:pressed {border-style: solid; border-width: 3px; border-color: rgb(14, 80, 158);} \n"
"QPushButton {background-color: rgb(255, 230, 31); color: rgb(14, 80, 158); border-radius: 10px; height: 40px;}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.name_line = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.name_line.setFont(font)
        self.name_line.setObjectName("name_line")
        self.verticalLayout.addWidget(self.name_line)
        self.wrong_name = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrong_name.sizePolicy().hasHeightForWidth())
        self.wrong_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(14)
        self.wrong_name.setFont(font)
        self.wrong_name.setStyleSheet("color: rgb(255, 115, 117)")
        self.wrong_name.setObjectName("wrong_name")
        self.verticalLayout.addWidget(self.wrong_name)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.email_line = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_line.sizePolicy().hasHeightForWidth())
        self.email_line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.email_line.setFont(font)
        self.email_line.setObjectName("email_line")
        self.verticalLayout.addWidget(self.email_line)
        self.wrong_email = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrong_email.sizePolicy().hasHeightForWidth())
        self.wrong_email.setSizePolicy(sizePolicy)
        self.wrong_email.setStyleSheet("color: rgb(255, 0, 4); font-size: 14pt;")
        self.wrong_email.setText("")
        self.wrong_email.setObjectName("wrong_email")
        self.verticalLayout.addWidget(self.wrong_email)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 5px;\n"
"width: 100px;\n"
"")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Регистрация"))
        self.label_2.setText(_translate("Dialog", "Введите имя"))
        self.wrong_name.setText(_translate("Dialog", "Имя должно состоять только из букв"))
        self.label.setText(_translate("Dialog", "Введите логин. Пароль будет сохранён в файле в каталоге программы"))
        self.email_line.setPlaceholderText(_translate("Dialog", "Обязательно вводите корректный логин"))
