# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_recover_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(743, 195)
        Dialog.setStyleSheet("QWidget {background-color: #1581e6; color: white; font-family: \"Days\";}\n"
"QPushButton:hover {border-style: solid; border-width: 3px; border-color: white;} QPushButton:pressed {border-style: solid; border-width: 3px; border-color: rgb(14, 80, 158);} \n"
"QPushButton {background-color: rgb(255, 230, 31); color: rgb(14, 80, 158); border-radius: 10px; height: 40px;}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.email_line = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_line.sizePolicy().hasHeightForWidth())
        self.email_line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.email_line.setFont(font)
        self.email_line.setObjectName("email_line")
        self.verticalLayout.addWidget(self.email_line)
        self.wrong_email = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrong_email.sizePolicy().hasHeightForWidth())
        self.wrong_email.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Days")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.wrong_email.setFont(font)
        self.wrong_email.setStyleSheet("color: rgb(255, 115, 117)")
        self.wrong_email.setObjectName("wrong_email")
        self.verticalLayout.addWidget(self.wrong_email)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.buttonBox.setFont(font)
        self.buttonBox.setStyleSheet("font: 63 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 5px;\n"
"width: 100px;\n"
"")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Восстановление пароля"))
        self.label.setText(_translate("Dialog", "Введите логин. Новый пароль будет сохранён в файле в каталоге программы"))
        self.email_line.setPlaceholderText(_translate("Dialog", "Обязательно вводите корректный логин"))
        self.wrong_email.setText(_translate("Dialog", "Несуществующий логин!"))
